# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: baf99fc52eeb003303f2465488ba31f881330d12c9449fb9420a756316202bfe08ec4966b9c237f98b7004e4e1f130346fb60b9b17812d9ac7fd0db6c3789fa5

test:
  secret_key_base: f78fbf11fbd0e967fee71ed223d26e7e34e0c3a97ee49174de458703cb8d297b67c8b91bad8f4d1d99752dbc8b2d07c4a1d445202cfe5cc4d9c4bc0bbf2d22e5

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
